### ISSUE TITLE
Disable unused tables?

### ISSUE THREAD

**Issue by defensivedepth** [polylogyx/osq-ext-bin#1]
I am looking for a way to disable tables, specifically some of the evented tables - 

It looks like the`--disable_tables=` flag works, but wanted to check and see if this was the best way to do this for the extension (?).

**Comment by manurautela** [comment]
Hi @defensivedepth , Thanks for opening the first ever issue of the extension.

And yes you are correct that using --disable_tables flag should disable the table from working.

Here is snapshot of how things should look. From the perspective of extension user won't be able to query this table's data.

![image](https://user-images.githubusercontent.com/1333906/45940049-614a8800-bff4-11e8-8715-413ca3950aa2.png)



Infact ,your issue just gave us an idea to optimize it further by not registering the callbacks to receive those evented table events from our kernel driver. So thanks for that. Will optimize this in next build.  

Please let us know if you face any issues with this.

**Comment by polylogyx** [comment]
👍

**Comment by defensivedepth** [comment]
Thanks much!
