### ISSUE TITLE
Feature Request: Add CreationFlags to win_process_events

### ISSUE THREAD

**Issue by zaneGittins** [polylogyx/osq-ext-bin#16]
Would be great to have visibility into the CreationFlags of processes. This would be really helpful to detect process hollowing, which typically creates a process in a suspended state.

**Comment by polylogyx** [comment]
Thank you for the feedback. Although I doubt if a process is created a suspended process,, then that information is available from its creation flags. I will look in to it. There is, however, an integration with memory scanning engine called pe-sieve and that can help detect hollowed processes.  The PolyLogyx extension provides 2 tables to scan running processes.

**Comment by zaneGittins** [comment]
It should be available in the process creation flags, for example in the below dwCreationFlags is set to CREATE_SUSPENDED.

```cpp
CreateProcessA(NULL, (LPSTR)"c:\\windows\\syswow64\\notepad.exe", NULL, NULL, TRUE, CREATE_SUSPENDED, NULL, NULL, si, pi);```

It's great the pe-sieve is integrated with the PolyLogyx extension, however I think there is still a lot of value in being able to use event based tables to detect suspended process creation.

**Comment by hyadav-eiq** [comment]
Noted for future releases. Thank you.
