### ISSUE TITLE
Question: Is this project still under development?

### ISSUE THREAD

**Issue by sean-scott-lr** [polylogyx/osq-ext-bin#19]
I was curious if this project is still under development.  I went to the website "www.polylogyx.com" and it appears to no longer exist.  ( maybe its just down? ).

Thank you!

**Comment by hyadav-eiq** [comment]
Hello,

The current repository is deprecated and the extension moved to its new home under EclecticIQ.
https://github.com/eclecticiq/osq-ext-bin/

Thank you.
