### ISSUE TITLE
PolylogyX extension crashing with query packs

### ISSUE THREAD

**Issue by ion-storm** [polylogyx/osq-ext-bin#2]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 20:51:43.034852  4924 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is Not-Supported, can be Error Prone: 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 20:51:46.171454 15688 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is 
<snip>

Any idea how to debug this?

**Comment by ion-storm** [comment]
some more info during ephemeral verbose logging:
I0926 20:59:11.617839 16848 scheduler.cpp:97] Executing scheduled query pack_network-connection-listening_Windows_Process_Network_Conn: select DISTINCT processes.name, processes.path, process_open_sockets.remote_address, process_open_sockets.remote_port from process_open_sockets LEFT JOIN processes ON process_open_sockets.pid = processes.pid WHERE process_open_sockets.remote_port != 0 AND processes.name != '';
I0926 20:59:15.613124 17600 watcher.cpp:629] Created and monitoring extension child (19412): C:\ProgramData\osquery\plgx_win_extension.ext.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 20:59:16.686251 19416 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is Not-Supported, can be Error Prone: 0
W0926 20:59:18.706851 17600 watcher.cpp:595] Extension respawning too quickly: C:\ProgramData\osquery\plgx_win_extension.ext.exe
I0926 20:59:18.730784 17600 watcher.cpp:629] Created and monitoring extension child (18516): C:\ProgramData\osquery\plgx_win_extension.ext.exe
I0926 20:59:18.991753 16848 scheduler.cpp:162] Found results for query: pack_network-connection-listening_Windows_Process_Network_Conn
I0926 20:59:19.060897 16848 scheduler.cpp:97] Executing scheduled query pack_unwanted-chrome-extensions_HolaVPN: SELECT * FROM users JOIN chrome_extensions USING (uid) WHERE identifier='gkojfkhlekighikafcpjkiklfbnlmeio';
W0926 20:59:19.159632 16848 virtual_table.cpp:987] The chrome_extensions table returns data based on the current user by default, consider JOINing against the users table
I0926 20:59:19.382037 16848 browser_utils.cpp:72] Could not parse JSON from: C:\Users\kweller\AppData\Local\Google\Chrome\User Data\Default\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\1.16.12_0\/_locales/en/messages.json

**Comment by ion-storm** [comment]
```
I0926 21:14:47.738669  8212 scheduler.cpp:97] Executing scheduled query pack_network-connection-listening_Windows_Process_Network_Conn: select DISTINCT processes.name, processes.path, process_open_sockets.remote_address, process_open_sockets.remote_port from process_open_sockets LEFT JOIN processes ON process_open_sockets.pid = processes.pid WHERE process_open_sockets.remote_port != 0 AND processes.name != '';
I0926 21:14:54.698078  3896 watcher.cpp:629] Created and monitoring extension child (18476): C:\ProgramData\osquery\plgx_win_extension.ext.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 21:14:54.979933 18948 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is Not-Supported, can be Error Prone: 0
I0926 21:14:55.042659  8212 scheduler.cpp:162] Found results for query: pack_network-connection-listening_Windows_Process_Network_Conn
I0926 21:14:55.099458  8212 scheduler.cpp:97] Executing scheduled query win_process_events: select * from win_process_events;
W0926 21:14:57.796690  3896 watcher.cpp:595] Extension respawning too quickly: C:\ProgramData\osquery\plgx_win_extension.ext.exe
I0926 21:14:57.820618  3896 watcher.cpp:629] Created and monitoring extension child (16336): C:\ProgramData\osquery\plgx_win_extension.ext.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 21:14:58.016093 10908 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is Not-Supported, can be Error Prone: 0
W0926 21:15:00.910964  3896 watcher.cpp:595] Extension respawning too quickly: C:\ProgramData\osquery\plgx_win_extension.ext.exe
I0926 21:15:00.936070  3896 watcher.cpp:629] Created and monitoring extension child (17168): C:\ProgramData\osquery\plgx_win_extension.ext.exe
I0926 21:15:02.180032  8212 scheduler.cpp:162] Found results for query: win_process_events
I0926 21:15:02.186870  8212 scheduler.cpp:97] Executing scheduled query win_http_events: select * from win_http_events;
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 21:15:02.436432  9708 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is Not-Supported, can be Error Prone: 0
I0926 21:15:02.480124 15548 powershell_events.cpp:122] Invalid character frequency map found, skipping computation
I0926 21:15:03.818655  8212 scheduler.cpp:162] Found results for query: win_http_events
I0926 21:15:04.064709  3896 watcher.cpp:629] Created and monitoring extension child (9944): C:\ProgramData\osquery\plgx_win_extension.ext.exe
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0926 21:15:04.131255  3992 plgx_win_extension.ext.cpp:599] Running multiple instances of extn is Not-Supported, can be Error Prone: 0
I0926 21:15:06.355794  8212 scheduler.cpp:97] Executing scheduled query win_remote_thread_events: select * from win_remote_thread_events;
W0926 21:15:07.193982  3896 watcher.cpp:595] Extension respawning too quickly: C:\ProgramData\osquery\plgx_win_extension.ext.exe
```

**Comment by ion-storm** [comment]
as a test I disabled some of the packs I am using from the osquery-attck github repo to see if those queries are interfering.  So far the polylogyx extension has not crashed.

**Comment by ion-storm** [comment]
Load all packs from https://github.com/teoseller/osquery-attck with the default polylogyx extensions/flags/modified config to include the packs to reproduce.

**Comment by polylogyx** [comment]
At the first look, it seems that one of the queries took quite long causing osquery to re-spawn the extension, but the extension is still alive. And with-in the extension, there is a safe-guard to not allow multiple invocations and that is result in the prints. osquery is thinking the extension came out too soon and is attempting again and again. Although besides the annoying chattiness, are you not getting the query results too? Can you share the flagsfile? I will try to repro it with the packs mentioned.

**Comment by polylogyx** [comment]
Also, the osquery.conf, just to get a sense of what queries from the extension are being run.

**Comment by ion-storm** [comment]
Attached is the osquery.zip with config and flags file, I am noticing randomness with osquery not logging at random

[osquery.zip](https://github.com/polylogyx/osq-ext-bin/files/2423979/osquery.zip)

**Comment by polylogyx** [comment]
Thank you.  I will load these up. At the glance, nothing obvious comes up. As I mentioned earlier, it is possible that one of the evented tables might have had too many entries for some reason causing osquery to try and respawn the extension, although it shouldn't have failed in anything except for annoying error messages. The other possibility could be that an earlier instance of extension somehow was hanging around. I have heard that with 3.3.0 there have been some fixes in the way the core works with extension.

**Comment by polylogyx** [comment]
We might have to try some creative options in the extension to be able to deal with it.

**Comment by polylogyx** [comment]
Do you see the crash with the latest extension 1.0.23.3?

**Comment by polylogyx** [comment]
@ion-storm , is this the same issue that you referred to in twitter? The only issue I am having is there are times when osquery is failing to load the extension and not much gets printed in the logs except that, well, it failed to load the extension. We are working on a solution for that. Is there any other issue you are facing with the latest extension?

**Comment by hyadav-eiq** [comment]
Please try latest extension 4.0.0.0 and let us know.

**Comment by hyadav-eiq** [comment]
Closing as no update on the issue and no crash observed on latest extension 4.0.
