### ISSUE TITLE
Add Performance Metrics to PolyLogyX Extension

### ISSUE THREAD

**Issue by ion-storm** [polylogyx/osq-ext-bin#4]
OSQuery does not currently support performance metrics like CPU utilization & Memory Utilization

PolyLogyX can pull this information from wmi:

`Get-WmiObject win32_processor | select LoadPercentage  |fl
`

**Comment by polylogyx** [comment]
Yes, this is something we have been contemplating too.

**Comment by manurautela** [comment]
@ion-storm we have added these additional tables and counters. 
Should be available in the next release soon.

**Comment by ion-storm** [comment]
Freakn awesome, good work guys

**Comment by polylogyx** [comment]
Try with the latest release 1.0.25.5

**Comment by atul-eiq** [comment]
Closing this issue with the addition of win_process_perf & win_mem_perf tables into the extension.
