### ISSUE TITLE
System resources

### ISSUE THREAD

**Issue by Tomasinjo** [polylogyx/osq-ext-bin#5]
Hi,
let me start saying we really like capabilities of this tool.

But we noticed impact to system resources. Based on our measurements, it consumes on average 25-30% CPU with spikes to 100%, even without scheduled queries.

We are managing osquery agents with Kolide Fleet. Here are the flags:
```
--enroll_secret_path=C:\ProgramData\osquery\skrivn.txt
--tls_server_certs=C:\ProgramData\osquery\certs\10.131.71.202_8080.pem
--tls_hostname=xxxxx:8080
--host_identifier=123
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=3
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10
--allow_unsafe
--database_dump=false
--schedule_default_interval=30
--pack_refresh_interval=30
--config_refresh=120
```

Is such behavior expected? I know the extention queries all sort of stuff in background, but is there a way to turn off some of the background queries we don't need?

**Comment by polylogyx** [comment]
Hi Tomasinjo,

Appreciate your feedback. Can you share the osquery config? Our extension is designed to capture all types of real time activities on the endpoint, and depending on the volume of activities on the system, it can get expensive. To minimize the load on resources, we added the filters. Are those filters enabled on your config? Additionally, in the upcoming release, we are enhancing the filters even more to drop some of the high CPU event captures (e.g. image certificates) and that would further boost the CPU perf. I guess that is what you are also alluding to.
But before, I would like to see the osquery.conf you are using, if that is something you can share.

Atul

**Comment by Tomasinjo** [comment]
Thanks for quick response. 
I was aware of sysmon-style filters in config file, but I didn't know they apply directly to kernel callbacks. 

Correct me if I am wrong, but doesn't line
`--config_tls_endpoint=/api/v1/osquery/config`
mean that osquery will acquire cofiguration from (in my case) Kolide fleet manager? If that is true, I cannot apply filters since Kolide does not support writting configuration (I think Kolide generates config based on selected packs and queries from GUI).

I did one more test with config (with filters applied) from this repo. Because of that I lost connection with Kolide, but the cpu usage went waay down to average of 4-5%, which is feasible.

If I imagine things correctly (I am new to osquery) I will need a more flexible fleet platform if I want to put it into production. I sent you guys my contact for evaluation of your fleet manager.

Regards,
Tom

**Comment by polylogyx** [comment]
Hi Tom,

Glad to know that with the filters the performance went into feasible range. I am not quite sure if kolide fleet provides a way of adding arbitrary config files. One option could be, if you want to continue using kolide as fleet is to change your config plugin to 'filesystem' and manually place osquery.conf file (with filters) on the local endpoint. You can get rid of the following lines in your flag file

--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10

And instead use:

--config_plugin=filesystem
--config_path=C:\ProgramData\osquery\osquery.conf

And leave the rest as it is. This will enroll your endpoing into kolide fleet for all the operations but pick the config from the local file.

Other option is we can share our fleet manager with you. It is currently under Beta. I will email you separately on that.

Thanks,
Atul

**Comment by manurautela** [comment]
@Tomasinjo we recently fixed quite a number of performance related issues along with few new tables. 
It would be really great to try the latest extension 1.0.24.4 in the repository. 

Please feel free to provide feedback as well.

**Comment by polylogyx** [comment]
The extension has had my iterations of performance improvements. I would close this issue unless there is any objection, for which I will wait next 4-5 days.

**Comment by atul-eiq** [comment]
Closing it out as have not heard of performance issues since last comment. If needed, please re-open the same.
