### ISSUE TITLE
Extension crashing both itself and osquery

### ISSUE THREAD

**Issue by agentsofshield** [polylogyx/osq-ext-bin#8]
### What operating system and version are you using?
Windows10 1803

### What version of osquery are you using?
v3.4.0

### What steps did you take to reproduce the issue?
After a few hours the ext crashes leading to one of two situations:
1. The osqueryd process is still up but does nothing, cannot be queried and doesn't talk to the fleet server.
2. The osqueryd process crashed and comes back normally with the ext unloaded. (this usually takes less than an hour)
* Seems like running `--enable_extensions_watchdog` helps but not always

### What did you expect to see?
The osqueryd process not crashing and the ext tables available at all times.

### What did you see instead?
After a while I see that the osqueryd process started writing logs to a new log file (when not connected to fleet) and in it all I see is `Error executing scheduled query win_xxx_xxx: Error running query: no such table: win_xxx_xxx`
Also before the process crashes (and doesn't come back) the logs go into a loop of
`Registering extension (plgx_win_win_extension, "pid", version=1.0.30, sdk=3.2.6)`
`Extension "pid" has duplicate plugin name: win_dns_events in registry: table`
`Could not add extension plgx_win_extension: Duplicate registry item: win_dns_events`

**Comment by polylogyx** [comment]
Is that consistently happening? The extension is built with 3.2.6 SDK and the osquery version here is 3.4.0

Is it possible to try with 3.2.6? And can you add '--verbose' flag in the osquery.flags so it can generate more logs?

We are creating a new version with a 3.4.0+ SDK (It took time as osquery's build system was getting revamped). 

3.4.0 also had changes in the folder paths (although technically that shouldn't matter as long as the osquery.flags is reflecting the changes). We will also run with 3.4.0

**Comment by hyadav-eiq** [comment]
Please try latest extension 4.0.0.0 and let us know.

**Comment by hyadav-eiq** [comment]
Closing as no update on the issue and no crash observed on latest extension 4.0.
