### ISSUE TITLE
Missing information on rename events

### ISSUE THREAD

**Issue by loyeglenn** [polylogyx/osq-ext-bin#9]
File rename events (which include soft deletes) do not include enough information for a FIM solution. The following is an example. By only providing the target path, we are not able to reliably determine what source path was actually changed. Would it be possible to have the source path added to the table for rename events? 

action : FILE_RENAME 
eid : 58088C93-98F5-4C46-B839-490300000000 
hashed : 1 
md5 : f2a0dce16d6091cc31629b65726a73b9 
pe_file : NO 
pid : 7816 
process_guid : 96EE5D7D-BF8D-11E9-9924-CC2F71072CDF 
process_name : C:\Windows\explorer.exe 
sha256 : ba8f8c312abdfb82bb7a701f7992476a592a0e3c9446df17de0e3b93ac31b567 
target_path : C:\$RECYCLE.BIN\S-1-5-21-582744695-439021496-1762445294-1001\$RP13UH3.png 
time : 1566274252 
uid : <snipped> 
utc_time : Tue Aug 20 04:10:52 2019 UTC

**Comment by polylogyx** [comment]
Will pick it up for the next release.

**Comment by polylogyx** [comment]
In the extension release 1.0.32.2, we have modified the file_rename table's target path to contain the original file name.

target_path
C:\poly-docs\eq-negotiations\IMG-20190921-WA0002.jpg.crdownload [Orig: C:\Users\akabra\Downloads\fe04f8d8-b306-444d-bc49-1af0f1cf89f3.tmp]

**Comment by polylogyx** [comment]
The target_path field contains the original file name as well.
